// Fixed creative package pricing tiers for Charm Systems (in ZAR).
export const creativePackages = [
  {
    id: "basic",
    name: "Basic",
    price: "R2,950",
    tagline: "A sharp, single-purpose creative presence.",
    highlighted: false,
    features: [
      "1-page responsive landing site",
      "Mobile + iPad optimized layout",
      "Core brand palette applied",
      "Contact / lead capture form",
      "7-day delivery",
    ],
    cta: "Start Basic",
  },
  {
    id: "growth",
    name: "Growth",
    price: "R6,950",
    tagline: "A multi-section creative portfolio that converts.",
    highlighted: true,
    features: [
      "Up to 5 responsive pages",
      "Smooth-scroll + motion micro-interactions",
      "Glassmorphic component system",
      "Basic CMS / content updates",
      "On-page SEO foundations",
      "14-day delivery",
    ],
    cta: "Choose Growth",
  },
  {
    id: "premium",
    name: "Premium",
    price: "R28,500",
    tagline: "A flagship creative platform with full production.",
    highlighted: false,
    features: [
      "Fully custom multi-page experience",
      "Advanced animation & scroll storytelling",
      "Bespoke design system + assets",
      "Integrations & automation hooks",
      "Performance-tuned for 60fps",
      "Priority 30-day support",
    ],
    cta: "Go Premium",
  },
];
